import { useEffect, useState } from 'react'
import { ArrowsClockwise, CalendarX, Database, Desktop, DownloadSimple, LockKey, Moon, Question, ShieldCheck, Sun, Trash, UploadSimple, WarningOctagon } from '@phosphor-icons/react'
import type { ActionResult, AppSnapshot, ThemeMode, UpdateStatus } from '@shared/types'
import { Badge, Button, Card, Field, Input, PageHeader } from '../components/ui'
import { cx } from '../lib/cx'

const states = [
  ['BW','Baden-Württemberg'],['BY','Bayern'],['BE','Berlin'],['BB','Brandenburg'],['HB','Bremen'],['HH','Hamburg'],['HE','Hessen'],['MV','Mecklenburg-Vorpommern'],['NI','Niedersachsen'],['NW','Nordrhein-Westfalen'],['RP','Rheinland-Pfalz'],['SL','Saarland'],['SN','Sachsen'],['ST','Sachsen-Anhalt'],['SH','Schleswig-Holstein'],['TH','Thüringen']
]

export function Settings({ data, report }: { data: AppSnapshot; report: (result: ActionResult) => boolean }) {
  const [form,setForm] = useState(data.settings)
  const [passphrase,setPassphrase] = useState('')
  const [closedDay,setClosedDay] = useState({date:'',name:''})
  const [update,setUpdate] = useState<UpdateStatus>({state:'idle',message:'Noch nicht geprüft.'})
  useEffect(()=>window.planBaer.events.onUpdateStatus(setUpdate),[])

  async function save() { report(await window.planBaer.settings.save(form)) }
  async function setTheme(theme:ThemeMode) { setForm({...form,theme}); report(await window.planBaer.theme.set(theme)) }
  async function resetDatabase() {
    const confirmed = window.confirm('Datenbank wirklich zurücksetzen? Team, Verträge, Dienstpläne, Abwesenheiten, Stundenkonto, eigene Schließtage und Schichtvorlagen werden unwiderruflich gelöscht. Einrichtung, Bundesland und Darstellung bleiben erhalten.')
    if (confirmed) report(await window.planBaer.settings.resetDatabase())
  }

  return <div className="page settings-page">
    <PageHeader eyebrow="PlanBär anpassen" title="Einstellungen" description="Einrichtung, Darstellung, Datensicherung und Updates verwalten." actions={<><Button variant="secondary" onClick={()=>window.dispatchEvent(new Event('planbaer:start-tour'))}><Question size={18}/> Einführung starten</Button><Button onClick={save}>Einstellungen speichern</Button></>} />
    <div className="settings-grid">
      <Card className="settings-card"><div className="settings-card__heading"><div className="settings-icon"><Desktop size={21}/></div><div><h2>Einrichtung</h2><p>Diese Angaben erscheinen im Dienstplan und PDF.</p></div></div><Field label="Name der Einrichtung"><Input value={form.institutionName} onChange={(e)=>setForm({...form,institutionName:e.target.value})}/></Field><Field label="Adresse"><textarea className="input textarea" rows={3} value={form.address} onChange={(e)=>setForm({...form,address:e.target.value})}/></Field><Field label="Bundesland" hint="Bestimmt die gesetzlichen Feiertage im Sollstundenmodell."><select className="input" value={form.stateCode} onChange={(e)=>setForm({...form,stateCode:e.target.value})}>{states.map(([code,name])=><option value={code} key={code}>{name}</option>)}</select></Field></Card>
      <Card className="settings-card"><div className="settings-card__heading"><div className="settings-icon"><Sun size={21}/></div><div><h2>Darstellung</h2><p>PlanBär kann der Windows-Einstellung folgen.</p></div></div><div className="theme-options">{([{id:'system',label:'System',icon:Desktop,detail:'Windows folgen'},{id:'light',label:'Hell',icon:Sun,detail:'Helle Oberfläche'},{id:'dark',label:'Dunkel',icon:Moon,detail:'Dunkle Oberfläche'}] as const).map((item)=>{const Icon=item.icon;return <button key={item.id} className={cx('theme-option',form.theme===item.id&&'theme-option--active')} aria-pressed={form.theme===item.id} onClick={()=>setTheme(item.id)}><Icon size={23}/><span><strong>{item.label}</strong><small>{item.detail}</small></span>{form.theme===item.id&&<span className="theme-check">✓</span>}</button>})}</div><div className="accessibility-note"><ShieldCheck size={20}/><div><strong>Windows-11-optimiert</strong><span>Mica, Hochkontrast, reduzierte Bewegung und Anzeigeskalierung werden berücksichtigt.</span></div></div></Card>
      <Card className="settings-card"><div className="settings-card__heading"><div className="settings-icon"><CalendarX size={21}/></div><div><h2>Eigene Schließtage</h2><p>Schließtage reduzieren das Soll wie gesetzliche Feiertage.</p></div></div><div className="closed-day-form"><Field label="Datum"><Input type="date" value={closedDay.date} onChange={(e)=>setClosedDay({...closedDay,date:e.target.value})}/></Field><Field label="Bezeichnung"><Input value={closedDay.name} onChange={(e)=>setClosedDay({...closedDay,name:e.target.value})} placeholder="z. B. Betriebsausflug"/></Field><Button disabled={!closedDay.date||closedDay.name.trim().length<2} onClick={async()=>{if(report(await window.planBaer.settings.saveClosedDay(closedDay))) setClosedDay({date:'',name:''})}}>Hinzufügen</Button></div>{data.customClosedDays.length?<ul className="closed-day-list">{data.customClosedDays.map((day)=><li key={day.date}><span><strong>{new Intl.DateTimeFormat('de-DE').format(new Date(`${day.date}T12:00:00`))}</strong><small>{day.name}</small></span><button className="icon-button" aria-label={`Schließtag ${day.name} löschen`} onClick={()=>void window.planBaer.settings.deleteClosedDay(day.date).then(report)}><Trash size={17}/></button></li>)}</ul>:<p className="settings-footnote">Noch keine eigenen Schließtage eingetragen.</p>}</Card>
      <Card className="settings-card"><div className="settings-card__heading"><div className="settings-icon"><LockKey size={21}/></div><div><h2>Datensicherung</h2><p>Portable Backups sind mit AES-256 verschlüsselt.</p></div></div><Field label="Backup-Passwort" hint="Mindestens acht Zeichen. Das Passwort wird nicht gespeichert."><Input type="password" autoComplete="new-password" value={passphrase} onChange={(e)=>setPassphrase(e.target.value)} placeholder="Sicheres Passwort"/></Field><div className="button-row"><Button variant="secondary" disabled={passphrase.length<8} onClick={()=>void window.planBaer.backup.export(passphrase).then(report)}><DownloadSimple size={18}/> Backup erstellen</Button><Button variant="secondary" disabled={passphrase.length<8} onClick={()=>{if(window.confirm('Die aktuellen Daten werden vor der Wiederherstellung zusätzlich gesichert. Fortfahren?')) void window.planBaer.backup.restore(passphrase).then(report)}}><UploadSimple size={18}/> Wiederherstellen</Button></div><div className="local-info"><span className="privacy-pill__dot"/><span>Zusätzlich werden bis zu sieben lokale, über Windows geschützte Sicherungen vorgehalten.</span></div></Card>
      <Card className="settings-card"><div className="settings-card__heading"><div className="settings-icon"><ArrowsClockwise size={21}/></div><div><h2>Updates</h2><p>Installierte Version {data.appVersion}</p></div></div><div className="update-status"><Badge tone={update.state==='error'?'danger':update.state==='ready'?'success':update.state==='downloading'?'info':'neutral'}>{update.state==='idle'?'Bereit':update.state==='checking'?'Prüfung':update.state==='downloading'?'Download':update.state==='ready'?'Verfügbar':update.state==='current'?'Aktuell':'Fehler'}</Badge><p>{update.message}</p>{update.state==='downloading'&&<div className="progress"><span style={{width:`${update.percent??10}%`}}/></div>}</div><div className="button-row"><Button variant="secondary" onClick={async()=>setUpdate(await window.planBaer.updates.check())}><ArrowsClockwise size={18}/> Jetzt prüfen</Button>{update.state==='ready'&&<Button onClick={()=>void window.planBaer.updates.install().then(report)}>Neu starten und installieren</Button>}</div><p className="settings-footnote">Die kostenlose Version ist nicht signiert. Windows kann beim Installer eine Warnung „Unbekannter Herausgeber“ anzeigen.</p></Card>
      <Card className="settings-card settings-card--danger"><div className="settings-card__heading"><div className="settings-icon settings-icon--danger"><Database size={21}/></div><div><h2>Datenbank zurücksetzen</h2><p>Entfernt alle Planungs- und Personaldaten und stellt die Standard-Schichtvorlagen wieder her.</p></div></div><div className="danger-note"><WarningOctagon size={20}/><span>Einrichtung, Adresse, Bundesland und Darstellung bleiben erhalten. Dieser Vorgang kann nicht rückgängig gemacht werden.</span></div><div><Button variant="danger" onClick={resetDatabase}><Trash size={18}/> Datenbank zurücksetzen</Button></div></Card>
    </div>
  </div>
}
